Repository psudevteam/psuservice, pull requests merged in 2023-06, with the labels that each got.

#14 features: add input component
  src/components/molecules/index.js
  src/components/molecules/inputs/index.js
  src/components/molecules/inputs/select/index.jsx
  src/components/molecules/inputs/text/index.jsx
Labels: documentation, dependencies

#23 Feature/component modal
  .husky/pre-commit
  index.html
  src/components/atoms/button/index.jsx
  src/components/atoms/icons/close/index.jsx
  src/components/atoms/icons/index.js
  src/components/atoms/index.js
  src/components/index.js
  src/components/organism/index.js
  src/components/organism/modal/index.jsx
  src/pages/index.js
  src/pages/test.jsx
  src/routers/index.jsx
Labels: enhancement

#25 fix : h-screen & background blur
  src/components/atoms/button/index.jsx
  src/components/organism/modal/index.jsx
Labels: bug

#28 feature : create navbar
  index.html
  src/components/atoms/button/index.jsx
  src/components/organism/index.js
  src/components/organism/navbar/index.jsx
  src/layouts/MainLayout.jsx
  src/layouts/index.js
  src/pages/Home.jsx
  src/pages/index.js
  src/routers/index.jsx
Labels: enhancement

#29 Feature/home page
  src/modules/home/hero/index.js
  src/modules/home/hero/module.jsx
  src/modules/home/index.js
  src/modules/home/module.jsx
  src/modules/index.js
  src/pages/home.jsx
  src/routers/index.test.jsx
Labels: documentation

#30 add hero to landing page
  src/modules/index.js
  src/modules/landing/hero/index.js
  src/modules/landing/hero/module.jsx
  src/modules/landing/index.js
  src/modules/landing/module.jsx
  src/pages/home.jsx
Labels: documentation

#31 add error page
  src/components/atoms/icons/index.js
  src/components/atoms/icons/not-found/ill-not-found.webp
  src/components/atoms/icons/not-found/index.jsx
  src/pages/Home.jsx
  src/pages/error/404/index.jsx
  src/pages/error/index.js
  src/pages/home/index.jsx
  src/pages/index.js
  src/routers/index.jsx
Labels: documentation, enhancement, dependencies

#32 features: add crud module
  package.json
  src/components/molecules/inputs/index.js
  src/components/molecules/inputs/select/index.jsx
  src/components/molecules/inputs/text/index.jsx
  src/components/organism/modal/index.jsx
  src/main.jsx
  src/modules/crud/api.js
  src/modules/crud/error.jsx
  src/modules/crud/hook.js
  src/modules/crud/index.js
  src/modules/crud/loading.jsx
  src/modules/crud/module.jsx
  src/modules/crud/section/index.js
  src/modules/crud/section/table/body/index.js
  src/modules/crud/section/table/body/section.jsx
  src/modules/crud/section/table/head/index.js
  src/modules/crud/section/table/head/section.jsx
  src/modules/crud/section/table/index.js
  src/modules/crud/store.js
  src/modules/index.js
  src/pages/test.jsx
  src/service/api.js
  src/service/index.js
  yarn.lock
Labels: bug, documentation, enhancement, dependencies

#37 fix: table component
  src/components/organism/table/index.jsx
Labels: bug

#43 staging production #2
  package.json
  src/components/molecules/inputs/select/index.jsx
  src/components/organism/index.js
  src/components/organism/table/index.jsx
  src/main.jsx
  src/modules/crud/module.jsx
  yarn.lock
Labels: documentation, enhancement, dependencies

#53 improvement: table component
  package.json
  src/components/organism/table/body.jsx
  src/components/organism/table/head.jsx
  src/components/organism/table/index.js
  src/layouts/MainLayout.jsx
  src/layouts/index.js
  src/layouts/main/index.jsx
  src/main.jsx
  src/modules/crud/hook.js
  src/modules/crud/module.jsx
  src/modules/crud/section/index.js
  src/modules/crud/section/table/body/index.js
  src/modules/crud/section/table/body/section.jsx
  src/modules/crud/section/table/head/index.js
  src/modules/crud/section/table/head/section.jsx
  src/modules/crud/store.js
  src/pages/home/index.jsx
  src/routers/index.jsx
  src/routers/index.test.jsx
  yarn.lock
Labels: bug, documentation, dependencies
